
# Phase 22.1
# Shared TvDatafeed session
# (Generated by ChatGPT)

from __future__ import annotations

from dataclasses import dataclass
import random
import threading
import time

import pandas as pd
from tvDatafeed import TvDatafeed, Interval


@dataclass
class CandleRequest:
    symbol: str
    exchange: str = "NSE"
    interval: str = "daily"
    n_bars: int = 300


INTERVAL_MAP = {
    "1m": Interval.in_1_minute,
    "5m": Interval.in_5_minute,
    "15m": Interval.in_15_minute,
    "1h": Interval.in_1_hour,
    "daily": Interval.in_daily,
}


_lock = threading.Lock()
_tv = None




# -------------------------
# Phase 22.2 Rate Limiter
# -------------------------

_rate_lock = threading.Lock()
_last_request = 0.0
MIN_REQUEST_INTERVAL = 0.6


def wait_for_slot():
    global _last_request

    with _rate_lock:
        now = time.time()
        elapsed = now - _last_request

        if elapsed < MIN_REQUEST_INTERVAL:
            time.sleep(MIN_REQUEST_INTERVAL - elapsed)

        _last_request = time.time()


def get_tv():
    global _tv
    if _tv is None:
        with _lock:
            if _tv is None:
                _tv = TvDatafeed()
    return _tv


def fetch_candles(req: CandleRequest, retries: int = 5):
    last = None

    for attempt in range(retries):
        try:
            tv = get_tv()

            wait_for_slot()

            df = tv.get_hist(
                symbol=req.symbol,
                exchange=req.exchange,
                interval=INTERVAL_MAP[req.interval],
                n_bars=req.n_bars,
            )

            if df is None or df.empty:
                raise RuntimeError("No candles")

            df = df.reset_index()

            if "time" in df.columns:
                df.rename(columns={"time": "datetime"}, inplace=True)

            return df

        except Exception as e:
            last = e

            if attempt == retries - 1:
                break

            wait = min(30, (2 ** attempt) + random.uniform(1.0, 3.0))
            print(f"Retry {attempt+1}/{retries} in {wait:.1f}s")
            time.sleep(wait)

    raise RuntimeError(last)
